version: "3.7"

services:
  havid-19:
    image: techblog/havid-19
    container_name: havid-19
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - SCHOOL_ID= #Your school id "semel mossad" (can be found in https://web.mashov.info/students/login)
      - USER_ID= #web.mashov.info/student user
      - USER_KEY= #web.mashov.info/student password
   ports:
      - "6700:6700"
